import type { Produto } from "../types";

export const PRODUTOS: Produto[] = [
  // Notebooks
  {
    id: "nb-001",
    nome: 'MacBook Pro 14" M3',
    descricao: "Chip M3, 16GB RAM, 512GB SSD, Tela Liquid Retina XDR",
    preco: 15999.0,
    categoriaId: "notebooks",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 15,
  },
  {
    id: "nb-002",
    nome: "Dell XPS 15",
    descricao: "Intel Core i7-13700H, 32GB RAM, 1TB SSD, RTX 4060",
    preco: 12499.0,
    categoriaId: "notebooks",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 8,
  },
  {
    id: "nb-003",
    nome: "Lenovo ThinkPad X1 Carbon",
    descricao: 'Intel Core i7-1365U, 16GB RAM, 512GB SSD, 14" WUXGA',
    preco: 9899.0,
    categoriaId: "notebooks",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 12,
  },
  {
    id: "nb-004",
    nome: "ASUS ROG Zephyrus G14",
    descricao: "AMD Ryzen 9 7940HS, 32GB RAM, 1TB SSD, RTX 4070",
    preco: 13999.0,
    categoriaId: "notebooks",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 6,
  },
  {
    id: "nb-005",
    nome: "Acer Predator Helios 16",
    descricao: "Intel Core i9-13900HX, 32GB RAM, 1TB SSD, RTX 4080",
    preco: 16499.0,
    categoriaId: "notebooks",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 4,
  },

  // Computadores Gamer
  {
    id: "pc-001",
    nome: "Alienware Aurora R15",
    descricao: "Intel Core i9-13900KF, 64GB RAM, RTX 4090, 2TB SSD",
    preco: 24999.0,
    categoriaId: "computadores-gamer",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 3,
  },
  {
    id: "pc-002",
    nome: "Corsair Vengeance i7400",
    descricao: "Intel Core i7-13700K, 32GB RAM, RTX 4070 Ti, 1TB SSD",
    preco: 14999.0,
    categoriaId: "computadores-gamer",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 7,
  },
  {
    id: "pc-003",
    nome: "NZXT Player Three Prime",
    descricao: "AMD Ryzen 9 7900X, 32GB RAM, RTX 4080, 2TB SSD",
    preco: 18999.0,
    categoriaId: "computadores-gamer",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 5,
  },
  {
    id: "pc-004",
    nome: "MSI Aegis RS",
    descricao: "Intel Core i7-13700KF, 32GB RAM, RTX 4070, 1TB SSD",
    preco: 13499.0,
    categoriaId: "computadores-gamer",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 9,
  },
  {
    id: "pc-005",
    nome: "HP OMEN 45L",
    descricao: "Intel Core i9-13900K, 64GB RAM, RTX 4090, 2TB SSD",
    preco: 26999.0,
    categoriaId: "computadores-gamer",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 2,
  },
  {
    id: "pc-006",
    nome: "Lenovo Legion Tower 7i",
    descricao: "Intel Core i9-13900KF, 32GB RAM, RTX 4080, 2TB SSD",
    preco: 19999.0,
    categoriaId: "computadores-gamer",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 6,
  },

  // Periféricos
  {
    id: "per-001",
    nome: "Logitech G Pro X Superlight",
    descricao: "Mouse Gamer Wireless, Sensor HERO 25K, 63g",
    preco: 899.0,
    categoriaId: "perifericos",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 25,
  },
  {
    id: "per-002",
    nome: "Razer BlackWidow V4 Pro",
    descricao: "Teclado Mecânico RGB, Switch Green, ABNT2",
    preco: 1499.0,
    categoriaId: "perifericos",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 18,
  },
  {
    id: "per-003",
    nome: "HyperX Cloud Alpha Wireless",
    descricao: "Headset Gamer, Som Surround 7.1, Bateria 300h",
    preco: 1299.0,
    categoriaId: "perifericos",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 14,
  },
  {
    id: "per-004",
    nome: "SteelSeries Arctis Nova Pro",
    descricao: "Headset Premium, DAC GameDAC Gen 2, Hi-Res Audio",
    preco: 2499.0,
    categoriaId: "perifericos",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 10,
  },
  {
    id: "per-005",
    nome: "Corsair K100 RGB",
    descricao: "Teclado Mecânico, Switch OPX, Roda iCUE",
    preco: 1899.0,
    categoriaId: "perifericos",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 12,
  },
  {
    id: "per-006",
    nome: "Logitech G502 X Plus",
    descricao: "Mouse Gamer Wireless, LIGHTFORCE, RGB LIGHTSYNC",
    preco: 749.0,
    categoriaId: "perifericos",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 20,
  },

  // Hardware
  {
    id: "hw-001",
    nome: "NVIDIA GeForce RTX 4090",
    descricao: "Placa de Vídeo 24GB GDDR6X, DLSS 3, Ray Tracing",
    preco: 12999.0,
    categoriaId: "hardware",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 5,
  },
  {
    id: "hw-002",
    nome: "AMD Ryzen 9 7950X",
    descricao: "Processador 16-Core, 32-Threads, 5.7GHz Boost",
    preco: 3499.0,
    categoriaId: "hardware",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 11,
  },
  {
    id: "hw-003",
    nome: "Samsung 990 PRO 2TB",
    descricao: "SSD NVMe Gen 4, 7450MB/s Leitura, PCIe 4.0",
    preco: 1299.0,
    categoriaId: "hardware",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 22,
  },
  {
    id: "hw-004",
    nome: "Corsair Dominator Platinum RGB 64GB",
    descricao: "Memória RAM DDR5 6000MHz, Kit 2x32GB, CL30",
    preco: 2899.0,
    categoriaId: "hardware",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 15,
  },
  {
    id: "hw-005",
    nome: "ASUS ROG Strix Z790-E",
    descricao: "Placa-Mãe Intel Z790, DDR5, PCIe 5.0, WiFi 6E",
    preco: 3299.0,
    categoriaId: "hardware",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 8,
  },
  {
    id: "hw-006",
    nome: "Corsair HX1500i",
    descricao: "Fonte 1500W, 80 Plus Platinum, Modular, Digital",
    preco: 2499.0,
    categoriaId: "hardware",
    imagem: "/images/produtos/placeholder.jpg",
    estoque: 13,
  },
];
