import type { Product } from "../types";

export const PRODUCTS: Product[] = [
  // Notebooks
  {
    id: "nb-001",
    name: 'MacBook Pro 14" M3',
    description: "Chip M3, 16GB RAM, 512GB SSD, Tela Liquid Retina XDR",
    price: 15999.0,
    category: "notebooks",
    image: "/images/products/notebooks/MacBookPro14M3.jpg",
    stock: 15,
  },
  {
    id: "nb-002",
    name: "Dell XPS 15",
    description: "Intel Core i7-13700H, 32GB RAM, 1TB SSD, RTX 4060",
    price: 12499.0,
    category: "notebooks",
    image: "/images/products/notebooks/DellXPS15.jpg",
    stock: 8,
  },
  {
    id: "nb-003",
    name: "Lenovo ThinkPad X1 Carbon",
    description: 'Intel Core i7-1365U, 16GB RAM, 512GB SSD, 14" WUXGA',
    price: 9899.0,
    category: "notebooks",
    image: "/images/products/notebooks/LenovoThinkPadX1Carbon.jpg",
    stock: 0,
  },
  {
    id: "nb-004",
    name: "ASUS ROG Zephyrus G14",
    description: "AMD Ryzen 9 7940HS, 32GB RAM, 1TB SSD, RTX 4070",
    price: 13999.0,
    category: "notebooks",
    image: "/images/products/notebooks/ASUSROGZephyrusG14.jpg",
    stock: 6,
  },
  {
    id: "nb-005",
    name: "Acer Predator Helios 16",
    description: "Intel Core i9-13900HX, 32GB RAM, 1TB SSD, RTX 4080",
    price: 16499.0,
    category: "notebooks",
    image: "/images/products/notebooks/AcerPredatorHelios16.jpg",
    stock: 4,
  },

  // Computadores Gamer
  {
    id: "pc-001",
    name: "Alienware Aurora R15",
    description: "Intel Core i9-13900KF, 64GB RAM, RTX 4090, 2TB SSD",
    price: 24999.0,
    category: "computadores-gamer",
    image: "/images/products/pc-gamer/AlienwareAuroraR15.jpg",
    stock: 0,
  },
  {
    id: "pc-002",
    name: "Corsair Vengeance i7400",
    description: "Intel Core i7-13700K, 32GB RAM, RTX 4070 Ti, 1TB SSD",
    price: 14999.0,
    category: "computadores-gamer",
    image: "/images/products/pc-gamer/Corsair Vengeance i7400.jpg",
    stock: 7,
  },
  {
    id: "pc-003",
    name: "NZXT Player Three Prime",
    description: "AMD Ryzen 9 7900X, 32GB RAM, RTX 4080, 2TB SSD",
    price: 18999.0,
    category: "computadores-gamer",
    image: "/images/products/pc-gamer/NZXT Player Three Prime.jpg",
    stock: 5,
  },
  {
    id: "pc-004",
    name: "MSI Aegis RS",
    description: "Intel Core i7-13700KF, 32GB RAM, RTX 4070, 1TB SSD",
    price: 13499.0,
    category: "computadores-gamer",
    image: "/images/products/pc-gamer/MSI Aegis RS.jpg",
    stock: 9,
  },
  {
    id: "pc-005",
    name: "HP OMEN 45L",
    description: "Intel Core i9-13900K, 64GB RAM, RTX 4090, 2TB SSD",
    price: 26999.0,
    category: "computadores-gamer",
    image: "/images/products/pc-gamer/HP OMEN 45L.jpg",
    stock: 2,
  },
  {
    id: "pc-006",
    name: "Lenovo Legion Tower 7i",
    description: "Intel Core i9-13900KF, 32GB RAM, RTX 4080, 2TB SSD",
    price: 19999.0,
    category: "computadores-gamer",
    image: "/images/products/pc-gamer/Lenovo Legion Tower 7i.jpg",
    stock: 6,
  },

  // Periféricos
  {
    id: "per-001",
    name: "Logitech G Pro X Superlight",
    description: "Mouse Gamer Wireless, Sensor HERO 25K, 63g",
    price: 899.0,
    category: "perifericos",
    image: "/images/products/perifericos/Logitech G Pro X Superlight.jpg",
    stock: 25,
  },
  {
    id: "per-002",
    name: "Razer BlackWidow V4 Pro",
    description: "Teclado Mecânico RGB, Switch Green, ABNT2",
    price: 1499.0,
    category: "perifericos",
    image: "/images/products/perifericos/Razer BlackWidow V4 Pro.jpg",
    stock: 0,
  },
  {
    id: "per-003",
    name: "HyperX Cloud Alpha Wireless",
    description: "Headset Gamer, Som Surround 7.1, Bateria 300h",
    price: 1299.0,
    category: "perifericos",
    image: "/images/products/perifericos/HyperX Cloud Alpha Wireless.jpg",
    stock: 14,
  },
  {
    id: "per-004",
    name: "SteelSeries Arctis Nova Pro",
    description: "Headset Premium, DAC GameDAC Gen 2, Hi-Res Audio",
    price: 2499.0,
    category: "perifericos",
    image: "/images/products/perifericos/SteelSeries Arctis Nova Pro.jpg",
    stock: 10,
  },
  {
    id: "per-005",
    name: "Corsair K100 RGB",
    description: "Teclado Mecânico, Switch OPX, Roda iCUE",
    price: 1899.0,
    category: "perifericos",
    image: "/images/products/perifericos/Corsair K100 RGB.jpg",
    stock: 12,
  },
  {
    id: "per-006",
    name: "Logitech G502 X Plus",
    description: "Mouse Gamer Wireless, LIGHTFORCE, RGB LIGHTSYNC",
    price: 749.0,
    category: "perifericos",
    image: "/images/products/perifericos/Logitech G502 X Plus.jpg",
    stock: 20,
  },

  // Hardware
  {
    id: "hw-001",
    name: "NVIDIA GeForce RTX 4090",
    description: "Placa de Vídeo 24GB GDDR6X, DLSS 3, Ray Tracing",
    price: 12999.0,
    category: "hardware",
    image: "/images/products/hardware/NVIDIA GeForce RTX 4090.jpg",
    stock: 5,
  },
  {
    id: "hw-002",
    name: "AMD Ryzen 9 7950X",
    description: "Processador 16-Core, 32-Threads, 5.7GHz Boost",
    price: 3499.0,
    category: "hardware",
    image: "/images/products/hardware/AMD Ryzen 9 7950X.jpg",
    stock: 11,
  },
  {
    id: "hw-003",
    name: "Samsung 990 PRO 2TB",
    description: "SSD NVMe Gen 4, 7450MB/s Leitura, PCIe 4.0",
    price: 1299.0,
    category: "hardware",
    image: "/images/products/hardware/Samsung 990 PRO 2TB.jpg",
    stock: 22,
  },
  {
    id: "hw-004",
    name: "Corsair Dominator Platinum RGB 64GB",
    description: "Memória RAM DDR5 6000MHz, Kit 2x32GB, CL30",
    price: 2899.0,
    category: "hardware",
    image: "/images/products/hardware/Corsair Dominator Platinum RGB 64GB.jpg",
    stock: 15,
  },
  {
    id: "hw-005",
    name: "ASUS ROG Strix Z790-E",
    description: "Placa-Mãe Intel Z790, DDR5, PCIe 5.0, WiFi 6E",
    price: 3299.0,
    category: "hardware",
    image: "/images/products/hardware/ASUS ROG Strix Z790-E.jpg",
    stock: 8,
  },
  {
    id: "hw-006",
    name: "Corsair HX1500i",
    description: "Fonte 1500W, 80 Plus Platinum, Modular, Digital",
    price: 2499.0,
    category: "hardware",
    image: "/images/products/hardware/Corsair HX1500i.jpg",
    stock: 0,
  },
];
